# Generated by Django 5.2.4 on 2026-06-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_type',
            field=models.CharField(choices=[('none', 'No Interactive Demo'), ('security', 'Security allocation'), ('scraping', 'Learning scraper')], default='none', max_length=20),
        ),
    ]
