# Generated by Django 5.2.4 on 2026-06-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_alter_project_demo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your physical PDF resume here', upload_to='resumes/'),
        ),
    ]
