import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { sendChat } from "../api";
import { usePortfolio } from "../context/PortfolioContext";
import { Send, X, Sparkles, RefreshCw } from "lucide-react";
interface Message { role: "user" | "assistant"; content: string; }
export const AIAssistant = () => {
  const { data: { personalInfo } } = usePortfolio();
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Hello! Ask me about Rajesh's listed skills or portfolio projects. Responses are AI-generated and should be confirmed directly." }]);
  const [inputMessage, setInputMessage] = useState(""); const [isLoading, setIsLoading] = useState(false); const [isOpen, setIsOpen] = useState(false); const messagesEndRef = useRef<HTMLDivElement>(null);
  const quickQuestions = ["What are your backend skills?", "Tell me about your projects.", "How can I contact Rajesh?", "Where did you study?"];
  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, isLoading]);
  useEffect(() => { const fn=(e: KeyboardEvent)=>e.key === "Escape" && setIsOpen(false); window.addEventListener("keydown", fn); return () => window.removeEventListener("keydown", fn); }, []);
  const ask = async (text: string) => { if (!text.trim() || isLoading) return; const next: Message = { role: "user", content: text.trim() }; const history = [...messages, next]; setMessages(history); setInputMessage(""); setIsLoading(true); try { const data = await sendChat({ messages: history, userMessage: next.content }); setMessages((p) => [...p, { role: "assistant", content: data.reply }]); } catch { setMessages((p) => [...p, { role: "assistant", content: `The assistant is unavailable. Please contact Rajesh at ${personalInfo.email}.` }]); } finally { setIsLoading(false); } };
  return <>
    {!isOpen && <div className="fixed bottom-6 right-6 z-50"><motion.button aria-label="Open AI assistant" onClick={() => setIsOpen(true)} whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }} className="flex items-center gap-2.5 px-4 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-full shadow-2xl transition-colors border border-indigo-400/20"><Sparkles className="w-5 h-5 animate-pulse text-indigo-200"/><span className="text-xs font-semibold tracking-wider uppercase font-mono">Talk to Rajesh AI</span><span className="w-2.5 h-2.5 bg-emerald-400 rounded-full animate-ping"/></motion.button></div>}
    <AnimatePresence>{isOpen && <div className="fixed bottom-4 left-4 right-4 sm:left-auto sm:right-6 sm:w-[400px] z-50"><motion.div role="dialog" aria-label="Rajesh AI portfolio assistant" initial={{ opacity: 0, y: 100, scale: .9 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 100, scale: .9 }} className="bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col h-[520px]">
      <div className="bg-gradient-to-r from-indigo-700 to-violet-600 px-4 py-3 flex items-center justify-between text-white shrink-0"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-full bg-slate-900/40 p-1.5 border border-indigo-400/30"><Sparkles className="w-full h-full text-indigo-200"/></div><div><h4 className="font-bold text-xs tracking-wider uppercase font-mono">Rajesh's AI Representative</h4><span className="text-[9px] text-indigo-200">AI-generated portfolio answers</span></div></div><button aria-label="Close AI assistant" onClick={() => setIsOpen(false)} className="w-7 h-7 rounded-full bg-black/10 flex items-center justify-center hover:bg-black/25"><X className="w-4 h-4"/></button></div>
      <div aria-live="polite" className="flex-1 overflow-y-auto p-4 space-y-3.5 bg-slate-950/70">{messages.map((m, i) => <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[85%] rounded-2xl px-3.5 py-2.5 text-xs leading-relaxed ${m.role === "user" ? "bg-indigo-600 text-white rounded-tr-none text-right" : "bg-slate-900 text-slate-300 border border-slate-800 rounded-tl-none"}`}>{m.content}</div></div>)}{isLoading && <div className="flex justify-start"><div className="bg-slate-900 text-slate-400 border border-slate-800 rounded-2xl px-3.5 py-2.5 text-xs flex items-center gap-2"><RefreshCw className="w-3.5 h-3.5 animate-spin text-indigo-400"/>Generating response...</div></div>}<div ref={messagesEndRef}/></div>
      <p className="px-4 pt-2 text-[9px] text-slate-500 bg-slate-950/40">Do not share sensitive information. Confirm important details directly.</p>
      <div className="px-4 py-2 bg-slate-950/40 border-t border-slate-800 overflow-x-auto shrink-0 flex gap-2 whitespace-nowrap">{quickQuestions.map((q) => <button key={q} onClick={() => ask(q)} disabled={isLoading} className="px-3 py-1.5 bg-slate-900 hover:bg-slate-800 text-slate-300 text-[10px] font-semibold border border-slate-800 rounded-full disabled:opacity-50">{q}</button>)}</div>
      <form onSubmit={(e) => { e.preventDefault(); ask(inputMessage); }} className="bg-slate-900 border-t border-slate-800 p-3 shrink-0 flex gap-2"><input aria-label="Ask a portfolio question" maxLength={800} disabled={isLoading} value={inputMessage} onChange={(e) => setInputMessage(e.target.value)} placeholder="Ask a portfolio question..." className="flex-1 bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2 text-xs focus:ring-1 focus:ring-indigo-500 focus:outline-none text-slate-200"/><button aria-label="Send question" type="submit" disabled={isLoading || !inputMessage.trim()} className="w-10 h-10 flex items-center justify-center bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl disabled:opacity-40"><Send className="w-4 h-4"/></button></form>
    </motion.div></div>}</AnimatePresence>
  </>;
};
